// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('m', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('m', async function() {
    await driver.get("https://www.polestar.com/us/")
    await driver.manage().window().setRect({ width: 818, height: 672 })
    await driver.findElement(By.id("helpButtonSpan")).click()
    {
      const element = await driver.findElement(By.id("helpButtonSpan"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    await driver.findElement(By.css(".slds-m-left_x-small:nth-child(3) > .slds-button")).click()
    await driver.findElement(By.css(".closeButton")).click()
    await driver.findElement(By.css(".dialog-button-0 > .label")).click()
  })
})
